name: Basic GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

      - name: Print Hello World
        run: echo "Hello World"

      - name: Create file
        run: touch myfile.txt

      - name: Write my name
        run: echo "Prabesh Upreti" > myfile.txt

      - name: Print my name
        run: cat myfile.txt

      - name: Add another line
        run: echo "I am learning GitHub Actions" >> myfile.txt

      - name: Print file again
        run: cat myfile.txt
